version: '3.8'
services:
  app:
    image: jmeter-demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
#    depends_on:
#      - service-db
    environment:
      - SERVER_PORT= 8081
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/books_db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

#  service-db:
#    image: postgres:14.7-alpine
#    environment:
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#    ports:
#      - "15432:5432"
#    volumes:
#      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
#      - db-data:/var/lib/postgresql/data
#    restart: unless-stopped

#  pgadmin:
#  container_name: pgadmin4_container
#  image: dpage/pgadmin4:7
#  restart: always
#  environment:
#    PGADMIN_DEFAULT_EMAIL: admin@admin.com
#    PGADMIN_DEFAULT_PASSWORD: root
#  ports:
#    - "5050:80"
#  volumes:
#    - pgadmin-data:/var/lib/pgadmin
#
#volumes:
#  db-data:
#  pgadmin-data: